name = "Simpleblue"
license = "MIT"
licenselink = "https://github.com/MarkKeeley/simpleblue/blob/master/LICENSE"
description = "A minimalist theme for Hugo"
homepage = "https://github.com/MarkKeeley/simpleblue"
tags = ["", ""]
features = ["", ""]
min_version = 0.16

[author]
  name = "Mark Keeley"
  homepage = "http://markkeeley.us"

